# Generated by Django 4.2.1 on 2023-06-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
    ]
