# Generated by Django 4.2.1 on 2023-06-14 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_spotifytoken_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spotifytoken',
            name='user',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
